/**
 * Central tool registry. Every PDF tool page, the homepage grid, the
 * router, and the sitemap generator all derive from this single source
 * of truth -- add a new tool here and it appears everywhere consistently.
 */
import type { ToolDefinition, ToolCategory } from "@/types";

export const TOOLS: ToolDefinition[] = [
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    shortDescription: "Combine PDFs in the order you want.",
    description: "Merge multiple PDF files into a single document, in exactly the order you choose. Drag to reorder before merging.",
    category: "organize",
    icon: "Combine",
    endpoint: "/pdf/merge",
    acceptedFileTypes: [".pdf"],
    multipleFiles: true,
    outputLabel: "Download merged PDF",
    color: "from-blue-500 to-indigo-600",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    shortDescription: "Extract every page into its own file.",
    description: "Split a PDF into individual single-page PDFs, delivered as a single ZIP download.",
    category: "organize",
    icon: "Scissors",
    endpoint: "/pdf/split",
    acceptedFileTypes: [".pdf"],
    multipleFiles: false,
    outputLabel: "Download split pages (.zip)",
    color: "from-emerald-500 to-teal-600",
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    shortDescription: "Shrink file size without losing quality.",
    description: "Reduce PDF file size by recompressing embedded images, with a quality preset you control.",
    category: "optimize",
    icon: "Archive",
    endpoint: "/pdf/compress",
    acceptedFileTypes: [".pdf"],
    multipleFiles: false,
    outputLabel: "Download compressed PDF",
    fields: [
      {
        name: "quality",
        label: "Compression level",
        type: "select",
        defaultValue: "recommended",
        options: [
          { label: "Low (smallest file)", value: "low" },
          { label: "Recommended", value: "recommended" },
          { label: "High (best quality)", value: "high" },
        ],
      },
    ],
    color: "from-orange-500 to-amber-600",
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    shortDescription: "Fix sideways or upside-down pages.",
    description: "Rotate all pages (or a specific range) of a PDF by 90, 180, or 270 degrees.",
    category: "edit",
    icon: "RotateCw",
    endpoint: "/pdf/rotate",
    acceptedFileTypes: [".pdf"],
    multipleFiles: false,
    outputLabel: "Download rotated PDF",
    fields: [
      {
        name: "angle",
        label: "Rotation angle",
        type: "select",
        defaultValue: "90",
        options: [
          { label: "90°", value: "90" },
          { label: "180°", value: "180" },
          { label: "270°", value: "270" },
        ],
      },
      { name: "pages", label: "Pages (optional, e.g. 1,3,5-8)", type: "text", placeholder: "All pages" },
    ],
    color: "from-purple-500 to-fuchsia-600",
  },
  {
    slug: "delete-pages",
    name: "Delete Pages",
    shortDescription: "Remove unwanted pages from a PDF.",
    description: "Delete one or more pages from a PDF by specifying page numbers or ranges.",
    category: "edit",
    icon: "FileMinus",
    endpoint: "/pdf/delete-pages",
    acceptedFileTypes: [".pdf"],
    multipleFiles: false,
    outputLabel: "Download edited PDF",
    fields: [{ name: "pages", label: "Pages to delete (e.g. 2,4,7-9)", type: "text", placeholder: "2,4,7-9" }],
    color: "from-rose-500 to-red-600",
  },
  {
    slug: "extract-pages",
    name: "Extract Pages",
    shortDescription: "Pull specific pages into a new PDF.",
    description: "Extract a chosen set of pages from a PDF into a brand new document.",
    category: "edit",
    icon: "FilePlus",
    endpoint: "/pdf/extract-pages",
    acceptedFileTypes: [".pdf"],
    multipleFiles: false,
    outputLabel: "Download extracted PDF",
    fields: [{ name: "pages", label: "Pages to extract (e.g. 1,3,5-8)", type: "text", placeholder: "1,3,5-8" }],
    color: "from-sky-500 to-cyan-600",
  },
  {
    slug: "rearrange-pages",
    name: "Rearrange Pages",
    shortDescription: "Reorder pages exactly how you want.",
    description: "Change the order of pages in a PDF by specifying the new page sequence.",
    category: "edit",
    icon: "ArrowLeftRight",
    endpoint: "/pdf/rearrange-pages",
    acceptedFileTypes: [".pdf"],
    multipleFiles: false,
    outputLabel: "Download rearranged PDF",
    fields: [{ name: "order", label: "New order, JSON array (e.g. [3,1,2])", type: "text", placeholder: "[3,1,2]" }],
    color: "from-violet-500 to-purple-600",
  },
  {
    slug: "watermark-pdf",
    name: "Watermark",
    shortDescription: "Stamp text across every page.",
    description: "Add a custom, semi-transparent text watermark across every page of your PDF.",
    category: "edit",
    icon: "Stamp",
    endpoint: "/pdf/watermark",
    acceptedFileTypes: [".pdf"],
    multipleFiles: false,
    outputLabel: "Download watermarked PDF",
    fields: [
      { name: "text", label: "Watermark text", type: "text", placeholder: "CONFIDENTIAL" },
      { name: "opacity", label: "Opacity", type: "range", defaultValue: 0.3, min: 0.05, max: 1, step: 0.05 },
      { name: "font_size", label: "Font size", type: "number", defaultValue: 40, min: 8, max: 200 },
      { name: "rotation", label: "Rotation (degrees)", type: "number", defaultValue: 45, min: 0, max: 360 },
    ],
    color: "from-slate-500 to-slate-700",
  },
  {
    slug: "page-numbers",
    name: "Page Numbers",
    shortDescription: "Add sequential numbers to every page.",
    description: "Stamp sequential page numbers onto your PDF, choosing position and starting number.",
    category: "edit",
    icon: "Hash",
    endpoint: "/pdf/page-numbers",
    acceptedFileTypes: [".pdf"],
    multipleFiles: false,
    outputLabel: "Download numbered PDF",
    fields: [
      {
        name: "position",
        label: "Position",
        type: "select",
        defaultValue: "bottom-center",
        options: [
          { label: "Bottom center", value: "bottom-center" },
          { label: "Bottom right", value: "bottom-right" },
          { label: "Bottom left", value: "bottom-left" },
          { label: "Top center", value: "top-center" },
          { label: "Top right", value: "top-right" },
          { label: "Top left", value: "top-left" },
        ],
      },
      { name: "start_number", label: "Start numbering at", type: "number", defaultValue: 1, min: 1 },
    ],
    color: "from-lime-500 to-green-600",
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    shortDescription: "Turn PDF pages into JPG images.",
    description: "Convert every page of a PDF into a high-quality JPG image, delivered as a ZIP.",
    category: "convert",
    icon: "Image",
    endpoint: "/image/pdf-to-jpg",
    acceptedFileTypes: [".pdf"],
    multipleFiles: false,
    outputLabel: "Download images (.zip)",
    color: "from-pink-500 to-rose-600",
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    shortDescription: "Combine JPG images into one PDF.",
    description: "Convert one or more JPG images into a single PDF document, one image per page.",
    category: "convert",
    icon: "ImagePlus",
    endpoint: "/image/jpg-to-pdf",
    acceptedFileTypes: [".jpg", ".jpeg"],
    multipleFiles: true,
    outputLabel: "Download PDF",
    color: "from-yellow-500 to-orange-600",
  },
  {
    slug: "png-to-pdf",
    name: "PNG to PDF",
    shortDescription: "Combine PNG images into one PDF.",
    description: "Convert one or more PNG images into a single PDF document, one image per page.",
    category: "convert",
    icon: "ImagePlus",
    endpoint: "/image/png-to-pdf",
    acceptedFileTypes: [".png"],
    multipleFiles: true,
    outputLabel: "Download PDF",
    color: "from-teal-500 to-cyan-600",
  },
  {
    slug: "pdf-to-png",
    name: "PDF to PNG",
    shortDescription: "Turn PDF pages into PNG images.",
    description: "Convert every page of a PDF into a lossless PNG image, delivered as a ZIP.",
    category: "convert",
    icon: "Image",
    endpoint: "/image/pdf-to-png",
    acceptedFileTypes: [".pdf"],
    multipleFiles: false,
    outputLabel: "Download images (.zip)",
    color: "from-indigo-500 to-blue-600",
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    shortDescription: "Convert PDF into an editable .docx.",
    description: "Convert a PDF into an editable Microsoft Word (.docx) document, preserving layout where possible.",
    category: "convert",
    icon: "FileText",
    endpoint: "/office/pdf-to-word",
    acceptedFileTypes: [".pdf"],
    multipleFiles: false,
    outputLabel: "Download Word document",
    color: "from-blue-600 to-blue-800",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    shortDescription: "Convert .docx into a PDF.",
    description: "Convert a Microsoft Word document into a shareable, universally-readable PDF.",
    category: "convert",
    icon: "FileText",
    endpoint: "/office/word-to-pdf",
    acceptedFileTypes: [".doc", ".docx"],
    multipleFiles: false,
    outputLabel: "Download PDF",
    color: "from-blue-700 to-indigo-800",
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    shortDescription: "Convert spreadsheets into a PDF.",
    description: "Convert an Excel spreadsheet into a print-ready, shareable PDF.",
    category: "convert",
    icon: "Sheet",
    endpoint: "/office/excel-to-pdf",
    acceptedFileTypes: [".xls", ".xlsx"],
    multipleFiles: false,
    outputLabel: "Download PDF",
    color: "from-green-600 to-emerald-700",
  },
  {
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    shortDescription: "Extract tables into a spreadsheet.",
    description: "Extract tabular data from a PDF into an editable Excel (.xlsx) spreadsheet.",
    category: "convert",
    icon: "Sheet",
    endpoint: "/office/pdf-to-excel",
    acceptedFileTypes: [".pdf"],
    multipleFiles: false,
    outputLabel: "Download spreadsheet",
    color: "from-green-700 to-teal-800",
  },
  {
    slug: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    shortDescription: "Convert slide decks into a PDF.",
    description: "Convert a PowerPoint presentation into a PDF, perfect for sharing and printing.",
    category: "convert",
    icon: "Presentation",
    endpoint: "/office/ppt-to-pdf",
    acceptedFileTypes: [".ppt", ".pptx"],
    multipleFiles: false,
    outputLabel: "Download PDF",
    color: "from-red-600 to-orange-700",
  },
];

export const getToolBySlug = (slug: string): ToolDefinition | undefined =>
  TOOLS.find((t) => t.slug === slug);

export const TOOL_CATEGORIES: { value: ToolCategory; label: string }[] = [
  { value: "organize", label: "Organize" },
  { value: "optimize", label: "Optimize" },
  { value: "convert", label: "Convert" },
  { value: "edit", label: "Edit" },
];
